name: Scan with OWASP Dependency Check

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["development"]
    paths:
      - 'main.yml' # Trigger this workflow when main.yml changes
      - '**/*' # Adjust to include other code changes as needed

jobs:
  depchecktest:
    name: Scan with OWASP Dependency Check
    runs-on: [ 'ubuntu-latest' ]
    
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      
      - name: Scan with OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'Mutillidae'
          path: '.'
          format: 'SARIF'
          out: '.'
          args: >
            --enableRetired
        continue-on-error: true
      
      - name: Upload results from OWASP Dependency Check to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@main
        with:
          sarif_file: dependency-check-report.sarif
          category: "Scan-dependencies-code-with-OWASP-Dependency-Check"
