name: TruffleHog Scan


on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches: ["development"]
    paths:
      - 'main.yml' # Trigger this workflow when main.yml changes
      - '**/*.py'  # Adjust to include other code changes as needed

jobs:
  trufflehog:
    name: Scan Application Code with Trufflehog OSS
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read
      security-events: write
    
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      
      - name: TruffleHog Enterprise scan
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:
          args: --fail-verified ${{ github.event.repository.default_branch }} HEAD
